name: release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Maven without tests (rely on upstream testing for now)
      run: mvn clean install -DskipTests
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "esvee/target/*.jar,hmf-common/target/*.jar"

  docker:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04-arm]
    needs: build
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        platforms: linux/amd64,linux/arm64
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
#    - name: Get git tag tool and version
#      run: |
#        TAG=${GITHUB_REF#refs/tags/}
#        TOOL=${TAG%-*}
#        VERSION=${TAG#*-}
#        echo "TOOL=$TOOL" >> $GITHUB_ENV
#        echo "VERSION=$VERSION" >> $GITHUB_ENV
    - name: Docker GitHub release
      uses: docker/build-push-action@v6
      with:
        context: .
        provenance: false
        file: ./esvee/Dockerfile
        platforms: ${{ matrix.platforms }}
#        build-args: VERSION=$VERSION
        build-args: |
          VERSION="1.0.2"
        push: true
#        tags: ghcr.io/umccr/hmftools-$TOOL:$VERSION-aarch64
        tags: ghcr.io/umccr/hmftools-esvee:1.0.2-aarch64
